server:
  port: 8080

spring:
  application:
    name: tbankApp
  datasource:
    url: jdbc:postgresql://db:5432/currency_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public